services:
  app:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db 
      DB_PORT: 3306
      DB_USER: swiftuser
      DB_PASSWORD: swiftpass
      DB_NAME: swiftdb

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swiftdb
      MYSQL_USER: swiftuser
      MYSQL_PASSWORD: swiftpass
    ports:
      - "3306:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  default:
    name: swift_network
    driver: bridge