networks:
  swift_network:
    driver: bridge

services:
  app:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db 
      DB_PORT: 3306
      DB_USER: swiftuser
      DB_PASSWORD: swiftpass
      DB_NAME: swiftdb
      DB_TESTNAME: testswiftdb
      DOCKERIZED: yes
      TESTING: no
    volumes:
      - ./docs:/app/docs
    networks:
      - swift_network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swiftdb
      MYSQL_USER: swiftuser
      MYSQL_PASSWORD: swiftpass
    ports:
      - "3307:3306" 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - swift_network
