FROM golang:1.24.1 AS builder
ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0

WORKDIR /build
COPY ./go.mod ./go.sum .
RUN go mod download

COPY ./src ./src
COPY ./data ./data

RUN chmod +x ./src

CMD ["/build/src/run_tests.sh"] 
